eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    status-page-url-path: /status
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-addr1}:${eureka-port1}/eureka,http://${eureka-addr2}:${eureka-port2}/eureka

filename: application.yml